stages:
  - build
  - sign

build rpm:
  image: almalinux:9
  stage: build
  script:
    - dnf install -y epel-release
    - dnf install -y git-core rpm-build rpmdevtools
    - mkdir -p rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS}
    - spectool -g zookeeper.spec
    - dnf builddep -y zookeeper.spec
    - rpmbuild --define "_topdir $(pwd)/rpmbuild" --define "_sourcedir $(pwd)" --define "_srcrpmdir $(pwd)" -bs --nodeps zookeeper.spec
    - rpmbuild --define "_topdir $(pwd)/rpmbuild" --define "_sourcedir $(pwd)" --define "_srcrpmdir $(pwd)" --rebuild *.src.rpm
    - echo "Build completed"
  artifacts:
    paths:
      - rpmbuild/RPMS/noarch/*.rpm
    expire_in: 1 week

sign rpm:
  stage: sign
  image: almalinux:9-minimal
  needs: ["build rpm"]
  script:
    - microdnf install -y rpm-sign
    - echo $DCACHE_ORG_PGP_KEY | base64 -d -i > secret.gpg
    - gpg --quiet --batch --yes --allow-secret-key-import --passphrase="$DCACHE_ORG_PGP_KEY_PASS" --import secret.gpg
    - gpg -a --export "$DCACHE_ORG_KEY_NAME" > RPM-GPG-KEY
    - rpmsign --addsign --define "_signature gpg" --define "_gpg_name  $DCACHE_ORG_KEY_NAME" --define "_gpg_sign_cmd_extra_args --pinentry-mode loopback --passphrase $DCACHE_ORG_PGP_KEY_PASS" rpmbuild/RPMS/noarch/*.rpm
    - rpmkeys --import RPM-GPG-KEY
    - rpm --checksig -v rpmbuild/RPMS/noarch/*.rpm
  artifacts:
    paths:
    - rpmbuild/RPMS/noarch/*.rpm